# Generated by Django 6.0.4 on 2026-05-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Dirección', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=10)),
                ('Titulo_academico', models.CharField(max_length=100)),
                ('Biografia', models.TextField(max_length=1000)),
                ('Correo_electronico', models.CharField(max_length=100)),
                ('Dedicacion_Personal', models.TextField(max_length=1000)),
            ],
        ),
    ]
