# Generated by Django 6.0.4 on 2026-05-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Apellidos',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Correo_electronico',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Dedicacion_Personal',
            new_name='dedicacion_personal',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Nombres',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Titulo_academico',
            new_name='titulo_academico',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='title',
        ),
    ]
