# Generated by Django 6.0.4 on 2026-05-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Proyectos',
        ),
    ]
