# Generated by Django 6.0.4 on 2026-05-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_portfolio_proyectos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Personas',
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
