# Generated by Django 6.0.4 on 2026-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_persona_personas_alter_personas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='img',
            field=models.ImageField(default=2, upload_to='portfolio/'),
            preserve_default=False,
        ),
    ]
