# Generated by Django 6.0.4 on 2026-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_proyectos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
