# Generated by Django 6.0.4 on 2026-05-16 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_proyectos_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'ordering': ['-created'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'ordering': ['-created'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='personas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectos',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Enlace del proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectos',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='biografia',
            field=models.TextField(max_length=1000, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='correo_electronico',
            field=models.CharField(max_length=100, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='dedicacion_personal',
            field=models.TextField(max_length=1000, verbose_name='Dedicación Personal'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='titulo_academico',
            field=models.CharField(max_length=100, verbose_name='Titulo Academico'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterModelTable(
            name='personas',
            table='personas',
        ),
        migrations.AlterModelTable(
            name='proyectos',
            table='proyectos',
        ),
    ]
